### ISSUE TITLE
Installation: module yaml has no attribute FullLoader

### ISSUE THREAD

**Issue by wrengs** [DessimozLab/read2tree#1]
Dear Authors, 

With great interest I have read your article on BioRxiv and was looking forward for an attempt myself on PacBio HiFi data of 4 different species. 
Following your detailed instructions, I have tried installing read2tree.
Since it is mentioned that read2tree was build and tested using python 3.5.1, I first created a python3.5 environment within conda.
Next I installed all mentioned modules. 

Upon attempting to test run read2tree as instructed, I received the following error:
AttributeError: module 'yaml' has no attribute 'FullLoader'

The FullLoader attribute was added to yaml version 5.1 ( https://pyyaml.org/wiki/PyYAML#history ) 
Thus I attempted installation of version 5.1, however got the error that my existing python installation was not compatible.

Specifications:
  - pyyaml==5.1 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
 
I am wondering if you could provide some more detailed information of the versions of the installed modules.
Additionally, the module filelock is not mentioned as an actual installation, but is mentioned to be needed.

Any further suggestions would be most welcome.
Thanks a lot in advance!

Kind regards,
Willem

**Comment by smajidian** [comment]
Dear Willem 
Thanks for your interest.  I'm sorry for the inconvenience.  I was able to reproduce the error with python 3.5 on linux. We'll update the readme soon. I just created a new conda env in linux with python 3.8 or 3.9 and ran read2tree successfully on the test dataset. Could you possibly consider using python 3.8 or 3.9?

Thanks for the comment on filelock which is installed by setup.py. As it can be installed by conda too, we'll update installation section in readme.

Please let us know whether it works for you or not.

Regards,
Sina

**Comment by wrengs** [comment]
Dear Sina,

Thank you kindly for the quick reply! 
I will have a go with python3.8 or 3.9 and keep you updated.

All the best,
Willem

**Comment by smajidian** [comment]
Dear Willem, 
My pleasure, I'm glad to hear that. So, I'm closing the issue but feel free to inform us if you have any other issues or questions.
Regards, Sina.
