### ISSUE TITLE
Unable to run multispecies test data

### ISSUE THREAD

**Issue by mo716** [DessimozLab/read2tree#10]
Hi! :) Thank you very much for this very innovative tool! I installed it along with the required dependencies; however, I am not able to run the five species test data somehow when running the command below:

`read2tree --tree --standalone_path marker_genes/ --reads sample_1.fastq sample_2.fastq --output_path output/`

Only the following subdirectories are made in the output directory: "01_ref_ogs_dna", "01_ref_ogs_aa", "02_ref_dna", "03_align_aa", "03_align_dna" and "04_mapping_sample_1". If I am not wrong, I think there should be more files and directories. The standard error (also attached in this post) displays this error in the final line:  

`TypeError: __init__() takes 2 positional arguments but 3 were given`

I would really appreciate if you could help or advise me in solving this. Please note that I ran the command in a computer cluster with a slurm engine, using sbatch. I exported "ngm" path in my bash script, the rest of the tools seem to be in already recognized bin paths. I am wondering if the error above might be linked to a path or tool that I should have exported (?).

Looking forward to hearing from you! 
Cheers!
[error.log](https://github.com/DessimozLab/read2tree/files/9476250/error.log)

**Comment by smajidian** [comment]
Dear @mo716 

Sorry for late reply. It seems that there is an issue with the `Mapping reads to species` step which uses [ngm](https://anaconda.org/bioconda/nextgenmap) and samtools. You may check whether these are installed correctly with `ngm --help` and `samtools --help`.

and could you please share the `mplog.log file` in the `output` folder with us ?
In the error log , I see that you use miniconda and python 3.7. Is there any chance that you could use python 3.8 or 3.9 (the recommended python version for the read2tree package)? 

I would also suggest to run it on it the test example takes few minutes with low memory. Of course it should work with slurm, but it could be easier to find the issue. You could also take a look at our [wiki](https://github.com/DessimozLab/read2tree/wiki) describing input and output.

Best regards,
Sina

**Comment by mo716** [comment]
Dear @sinamajidian ,

Thank you very much for you help and sorry for my late response! I totally missed the python recommendation (my bad). I made a conda environment having python 3.9.0, then activate it and followed the read2tee installations guideline. The multiple species test is running fine! :) Thank you very much! Regards.

**Comment by sinamajidian** [comment]
My pleasure, glad to hear that! 

Regards,
Sina
