### ISSUE TITLE
dna_reference for many species

### ISSUE THREAD

**Issue by ailtonpcf** [DessimozLab/read2tree#11]
To whom it may concern,

I'm trying to use read2tree in a hpc where I have no connection with internet. I'm trying to supply 3 genomes:
- Aspergillus clavatus (strain ATCC 1007 / CBS 513.65 / DSM 816 / NCTC 3887 / NRRL 1)
-Neosartorya fischeri (strain ATCC 1020 / DSM 3700 / CBS 544.65 / FGSC A1164 / JCM 1740 / NRRL 181 / WB 181)
-Neosartorya fumigata (strain ATCC MYA-4609 / Af293 / CBS 101355 / FGSC A1100)

using "dna_reference" 3 times, but the tool ignores and try to download the genomes anyway and then it crashes, since I have no internet connection. I also tried to create a multifasta with the 3 genomes merged but it also did not work. The genomes come from fungidb(https://fungidb.org/fungidb/app). I was planing to download the genomes from ensembl fungi, but Neosartorya fischeri is not available there. Does anyone know how to approach the multiple genome input, or how read2tree expects the genome fasta to be formatted? It recognizes the genome by file name or header?

Thanks in advance,
Ailton.

**Comment by sinamajidian** [comment]
Dear @ailtonpcf 
As you may know read2tree uses the orthologous groups that should be provided by the user. These fasta files include the amino acid (aa) sequences.  The current implementation needs the Internet for downloading the cdna version for each of these  aa sequence (based on the oma standard header of each record of fasta file) using OMA API. 
You may try to run the read2tree once on a system with the internet (with correct OG set but sample small genome) and re-use the orthologous groups for another run (with downloaded OG (aa+cdna) and your real genome) . I haven't tried it myself but in principle it should work.
Regards, Sina.

**Comment by alpae** [comment]
Hi @ailtonpcf 

Indeed, read2tree requires reference orthologous groups. We provide guidance how to get them using the OMA browser: [https://github.com/DessimozLab/read2tree/wiki/obtaining-marker-genes/](https://github.com/DessimozLab/read2tree/wiki/obtaining-marker-genes/). The method will need the amino acids sequences and the coding sequences (CDS) of those marker genes. The format that is required is to have for each orthologous group a fasta file with the amino acid sequences and and a single fasta file with all the cds sequences. you can then use the a command of the following form:

    Read2Tree --reference --standalone ../marker_genes/ --dna_reference <path/to/cds.fasta>

where `marker_genes` contains the folder with all the orthologous groups files.
