### ISSUE TITLE
Read2tree doesn't work if the folder with marker genes is not named "marker_genes"

### ISSUE THREAD

**Issue by shelkmike** [DessimozLab/read2tree#12]
Read2tree has an option "--standalone_path" which allows to provide a path to the folder with marker genes. However, if this folder has a name other than "marker_genes", Read2tree won't work. Since this is not documented, this probably should be considered a bug. Tested on Read2tree v0.1.3.

**Comment by alpae** [comment]
Hi @shelkmike 
thanks for reporting. indeed, this is not ideal. I'll have a look to how to improve this - probably by adding another parameter to the command line interface.
