### ISSUE TITLE
[Question] Marker gene for only one species

### ISSUE THREAD

**Issue by llk578496** [DessimozLab/read2tree#21]
Hello! We just tried to download the marker gene for _Candida auris_ but seems it can't. May I know is it possible to download the market gene for only one species? 

Thank you very much!
Eddie

**Comment by sinamajidian** [comment]
Hi Eddie 

Thanks for using read2tree. I'm afraid that it is not possible to to have marker genes for only on species. By definition,  each orthologous group (marker genes) should include more than one gene. 
I would suggest to include several species/strains from the same clade of your samples (sequencing reads) in addition to a few outgroup species to infer a reasonable phylogeny. 

Regards,
Sina

**Comment by llk578496** [comment]
I see. Thank a lot!
