### ISSUE TITLE
ete3 install needs changing

### ISSUE THREAD

**Issue by nikishe** [DessimozLab/read2tree#29]
I think in the install from source , you may need to update the initial step to 

conda install -c etetoolkit ete3

condaforge seems to not have ete3 anymore , though might have been a problem specific to my set up

**Comment by sinamajidian** [comment]
Hi
Thanks for using read2tree.

It should be possible to install from both channels : etetoolkit and conda-forge.
https://anaconda.org/conda-forge/ete3

Best regards,
Sina

**Comment by nikishe** [comment]
You are right , Its now working . I think initial issue was due to my set up . Thanks for the prompt response
