### ISSUE TITLE
bacteria_markergenes also mammalia

### ISSUE THREAD

**Issue by ewaltari** [DessimozLab/read2tree#30]
Hi - the bacteria_markergenes.zip file contains the mammalian marker genes (indeed is the exact same size as mammalia_markergenes.zip).

**Comment by sinamajidian** [comment]
Dear @ewaltari 

Thanks for reporting the case. That's true and there must have been an issue when I was creating the bacteria file. I've just uploaded the correct version of bacteria gene markers to the github [repo](https://github.com/DessimozLab/read2tree/tree/main/archive/set_marker_genes) and I'm sorry for the inconvenience.  

Please let us know if face any other issues. I hope that you will have a great experience using read2tree from now on :)


Best regards,
Sina
