### ISSUE TITLE
error  when map rna-seq to OMA db

### ISSUE THREAD

**Issue by catslu** [DessimozLab/read2tree#31]
Dear developers,
I had installed r2t by conda, downloaded the markers of Mollusca with 3 species genome via OMA db online. 
Now I am testing r2t using Mytilus spp. transcriptome data, only one paired , generated by illunima Noveseq 6000 platform with 150bp x2，i running with follow: 
read2tree --tree --standalone_path ../others_rna/r2t/ --reads SCK-1.trim_1.fq.gz SCK-2.trim_2.fq.gz --threads 40 --output_path ./r2t_test

for warning : 
`2023-06-19 12:38:35,686 - read2tree.Mapper - INFO - SCK-1: --- Mapping of reads to CRAGI reference species ---
/home/gene/liuxl/miniconda3/envs/sc/lib/python3.10/subprocess.py:959: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/home/gene/liuxl/miniconda3/envs/sc/lib/python3.10/subprocess.py:964: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)`

warning is ok?

**Comment by sinamajidian** [comment]
Hi @catslu 
Thanks for using Reed2Tree. Yes, this warning is fine and you can ignore it.

Best regards,
Sina
