### ISSUE TITLE
[Question] Are very short insert sizes an issue?

### ISSUE THREAD

**Issue by mptrsen** [DessimozLab/read2tree#37]
I'm going to process a bunch of sequencing datasets from museum samples, some stored under horrendous conditions and for decades. As a result, the DNA fragments are very short, often shorter than a read length. So we will have many read pairs that overlap partly or fully.

![FL_plots](https://imgur.com/rUDJlwX.png)

Is this an issue for the local assembly/will read2tree work with such samples?

**Comment by alpae** [comment]
Dear @mptrsen 

we don't have experience with such degenerated samples, but I suggest to just give it a try. In our experience, the coverage needed is very low, so I would hope that read2tree can deal with this.

**Comment by mptrsen** [comment]
Yes, coverage won't be an issue, just the fragmentation. I understand from the [read2tree paper](https://www.nature.com/articles/s41587-023-01753-4#Sec8) that the "local assembly" step consists in taking the consensus sequence from the mapped reads. So the insert size should be irrelevant to the method, because there is no "traditional" assembler in the pipeline that would use the insert size metric somehow. Is that correct?

**Comment by sinamajidian** [comment]
Thanks.  We also have a step to map the sequencing reads onto the orthologous groups using the [nextgenmap](https://academic.oup.com/bioinformatics/article/29/21/2790/195626) software for short reads. You can check its [wiki](https://github.com/Cibiv/NextGenMap/wiki/Documentation). We could provide you with some adjustment by changing some parts of [our code](https://github.com/DessimozLab/read2tree/blob/aaabf679d534b2c931d3d026dc8a9e4051b96dc6/read2tree/wrappers/read_mappers/ngm.py#L136) to benefit from NGM arugments.

**Comment by mptrsen** [comment]
@sinamajidian Thanks for the info. Since read2tree uses neither the `-I/ --min-insert-size` nor the `-X/ --max-insert-size` option for NGM, I assume that it runs with the defaults, i.e. insert size between 0 and 1000 bp.

Out of interest: Why use nextgenmap instead of a different mapper such as BWA, Bowtie, or bbmap? (There was little detail about the methods in the paper.)

**Comment by sinamajidian** [comment]
You're welcome.

The project started a few years ago, and NGM was among the best at the time. Besides, Fritz in the read2tree team was among the NGM's developers. 

Best regards,
Sina
