### ISSUE TITLE
can read2tree be used on metagenomiocs sample

### ISSUE THREAD

**Issue by Rohit-Satyam** [DessimozLab/read2tree#4]
Hi Developers!!

I wish to use read2tree on my metagenomics samples. Is it valid to do so?? Also, How do I get marker genes from OMA for all bacteria/ archaea ? are the ones under cDNA Prokaryotes at https://omabrowser.org/oma/current/ to be used??

Thanks!!

**Comment by smajidian** [comment]
Dear Rohit Satyam

Thanks for reaching out. Unfortunately, it is not possible to use read2tree for a sample (a fastq file) containing multiple species at the moment. But we have some ideas to expand the method for such case which will be implemented in near future. If you are interested in collaboration on this project, let us know by email. 

And about second question, please use this link https://omabrowser.org/oma/export_markers/ to download marker genes by selecting some species of interest and set the "Minimum fraction of covered species" to 0.8 and "Maximum nr of markers " to 1000 or -1.

Let me know if you have any other questions.  

Regards,
Sina
