### ISSUE TITLE
dna_reference not parsed when file extension is not .fa

### ISSUE THREAD

**Issue by Banthandor** [DessimozLab/read2tree#44]
Hi, 

I tried using the `--dna_reference` option, but the argument was never parsed and directly started using REST api to download the corresponding dna seq. The file had a `.fna` extension, but this prevented the option from being used. 

Changing the extension to `.fa` resolved the issue. 

You might want to make this clear in the wiki or make this option more dynamic.

Kind regards,
Sam

**Comment by sinamajidian** [comment]
Dear Sam

Thanks for your feedback. I've updated the wiki. 

Best regards,
Sina
