### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by laseulefourmie** [DessimozLab/read2tree#48]
Unfortunately, the installation with conda fails on our Linux system  Ubuntu 16.04.7 LTS. After creating and activating a conda environment as suggested in the installation manual on github, I get:

`conda install -c bioconda  read2tree
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                      failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0

Your installed version is: 2.27
`

Any advice would be greatly appreciated.

**Comment by sinamajidian** [comment]
Dear 
Thanks for using read2tree. Please try installation [from source](https://github.com/DessimozLab/read2tree#3-installation-from-source)
or use mamba `mamba create -n r2t -c conda-forge -c bioconda python=3.10.8 read2tree`.
Please let us know the result.

**Comment by laseulefourmie** [comment]
Dear Sina,


thanks.

installation with mamba worked, from source did not work.


Best,
Lukas

FREIE UNIVERSITÄT BERLIN / FREE UNIVERSITY OF BERLIN
Pharmazeutische Biologie / Pharmaceutical Biology
Königin-Luise-Str. 2+4,
D-14195 Berlin

________________________________
Von: Sina Majidian ***@***.***>
Gesendet: Donnerstag, 19. Oktober 2023 09:21:39
An: DessimozLab/read2tree
Cc: Koch, Lukas; Author
Betreff: Re: [DessimozLab/read2tree] installation error (Issue #48)


Dear
Thanks for using read2tree. Please try installation from source<https://github.com/DessimozLab/read2tree#3-installation-from-source>
or use mamba mamba create -n r2t -c conda-forge -c bioconda python=3.10.8 read2tree.
Please let us know the result.
