### ISSUE TITLE
Only R1 reads mapped for paired-end read input?

### ISSUE THREAD

**Issue by Yuqia** [DessimozLab/read2tree#50]
Hello,

I input 2 paired-end read files for the **--reads** option, separated by a space, but only the name of the R1 reads were shown in the _mplog.log_ file and in all output files/folders. 

Does this mean that only R1 reads were mapped? 

Do I need to use the option _--check_mate_pairing_ in order for both R1 and R2 reads are used in mapping?

Thank you very much!
Best,
Yuqia

**Comment by sinamajidian** [comment]
Hi Yuqia
Both of the reads (R1 and R2) are being used. That's only the naming and no other option is needed. Using  ` --debug` option you can see the exact command line that is run using aligner.  
Best regards,
Sina

**Comment by Yuqia** [comment]
Many thanks Sina!
Best,
Yuqia
