### ISSUE TITLE
Provide the dna and aa partitions in the output alignment

### ISSUE THREAD

**Issue by ArielRodrig** [DessimozLab/read2tree#55]
I thank the developers for their great work making read2tree. I see a great potential in the software. In order to extend the applicability in phylogenetic inferences it would be good to have the nucleotide and amino acid positions delimiting the genes in the output alignment of sequences. Among other applications, this feature will allow for the implementation of more refined substitution models during tree inference searches.
Thanks in advance,

**Comment by sinamajidian** [comment]
Thanks for suggestion. We have implemented the feature and it is ready to use using the latest Github commit.
