### ISSUE TITLE
Trouble in downloading OMA database

### ISSUE THREAD

**Issue by xuliuouc** [DessimozLab/read2tree#56]
Hi,

Thank you for your great work on this amazing software. 
I'm having trouble downloading marker genes through the OMA database (https://omabrowser.org/oma/export_markers).
When I chose the species I wanted and hit the 'submit' button, the browser opened another OMA tag (https://omabrowser.org/oma/export_markers) but didn't start downloading any data (waited for long enough). 
I've tried every device I have, including Win11 and Win10 with MS Edge and Chrome, Andriod, MacBook with Chrome and Safari, and Ubuntu with Firefox, but none of them worked. 
Could you please tell me where possible went wrong? 

Thank you in advance.

**Comment by alpae** [comment]
Hi @xuliuouc 

we had some issues yesterday with the webserver. It should be fixed now. Could you please retry and let me know in case the problem still remains. 

Best Adrian

**Comment by xuliuouc** [comment]
> Hi @xuliuouc
> 
> we had some issues yesterday with the webserver. It should be fixed now. Could you please retry and let me know in case the problem still remains.
> 
> Best Adrian

Dear Adrian,

Thank you for your reply. 
I'm afraid that the problem remains, just like yesterday.

Best,
Xu

**Comment by sinamajidian** [comment]
Could you please try for a few prokaryotic species? I just tried it, and it took a few seconds. 

<img width="400" alt="Screenshot 2024-01-24 at 14 12 59" src="https://github.com/DessimozLab/read2tree/assets/41860044/7b2f5abd-f1c0-42d8-b8bf-df3229901a13">

<img width="400" alt="Screenshot 2024-01-24 at 14 13 07" src="https://github.com/DessimozLab/read2tree/assets/41860044/c6773f54-55c9-4c3d-84ef-948b28bc2d97">

<img width="400" alt="Screenshot 2024-01-24 at 14 13 13" src="https://github.com/DessimozLab/read2tree/assets/41860044/8cbcd13d-445b-4db3-b1aa-aea0a02e5aea">

**Comment by xuliuouc** [comment]
> Could you please try for a few prokaryotic species? I just tried it, and it took a few seconds.
> 
> <img alt="Screenshot 2024-01-24 at 14 12 59" width="400" src="https://private-user-images.githubusercontent.com/41860044/299324002-7b2f5abd-f1c0-42d8-b8bf-df3229901a13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDI0NDIsIm5iZiI6MTcwNjEwMjE0MiwicGF0aCI6Ii80MTg2MDA0NC8yOTkzMjQwMDItN2IyZjVhYmQtZjFjMC00MmQ4LWI4YmYtZGYzMjI5OTAxYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEzMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MmZhNzc1OWFlZmEwMWYwNmIwY2JmNzgwODU4MjU1Zjg3MDMwNThlZDc3ZDI3NDFiNjZjNjY4MGQ1NDY2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WmmzsNv5rfk84Woh0KT6dfTWd4uWeEubJKxvS3QEp5c"> <img alt="Screenshot 2024-01-24 at 14 13 07" width="400" src="https://private-user-images.githubusercontent.com/41860044/299323999-c6773f54-55c9-4c3d-84ef-948b28bc2d97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDI0NDIsIm5iZiI6MTcwNjEwMjE0MiwicGF0aCI6Ii80MTg2MDA0NC8yOTkzMjM5OTktYzY3NzNmNTQtNTVjOS00YzNkLTg0ZWYtOTQ4YjI4YmMyZDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEzMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMmViYjlkYWFhN2E3MDg2NzY5YjcxYTU4YjgxMTg3MDdjMjkwODM1OTYzY2FhYzliMGNlYzk2OWFiMjhhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UPHe7hRMD56TV9HIhhWt-5CrW64PC3xkqhatkfffWc"> <img alt="Screenshot 2024-01-24 at 14 13 13" width="400" src="https://private-user-images.githubusercontent.com/41860044/299323987-8cbcd13d-445b-4db3-b1aa-aea0a02e5aea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDI0NDIsIm5iZiI6MTcwNjEwMjE0MiwicGF0aCI6Ii80MTg2MDA0NC8yOTkzMjM5ODctOGNiY2QxM2QtNDQ1Yi00ZGIzLWIxYWEtYWVhMGEwMmU1YWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEzMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NGFmNzAyZDhhOWEyYmFkMWQzM2QwZGE2M2RjYzg4ODVjZGM1MTQwYTE4MWJiNGU0OWVmYjRhYmY2ZGI1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8h0FKvWczY_rSDLncTCQ9PTWAVIJpwJklqtmF1zOp5g">

Wow, it works.
Thank you, and I think I know where the problem is. I only selected one species for testing, so it would not start downloading. That is a dumb question I asked.
Thank you all for your patience. LOL

**Comment by sinamajidian** [comment]
No worries :) Please let us know if you have any other questions. I'm closing this issue for now.
