### ISSUE TITLE
read2tree.wrappers.aligners.mafft -Warning- No alignments generated

### ISSUE THREAD

**Issue by wrengs** [DessimozLab/read2tree#6]
Dear Developers, dear Sina,

Previously, I installed and ran read2tree (test folder) within a python3.9 environment successfully. 

Currently, I am trying to run the tool on HiFi data of 4 species, but am running into an error with the MAFFT wrapper.

2022-08-16 14:19:06,956 - read2tree.ReferenceSet - INFO - : Extracted 2 reference species form 14506 ogs took 0.12563514709472656
--- Alignment of 14506 OGs ---
2022-08-16 14:19:23,896 - read2tree.wrappers.aligners.mafft - WARNING - is MAFFT_BINARIES set correctly: 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/netscratch/dep_mercier/grp_underwood/software2/anaconda3/envs/read2tree/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/netscratch/dep_mercier/grp_underwood/software2/anaconda3/envs/read2tree/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/netscratch/dep_mercier/grp_underwood/software2/anaconda3/envs/read2tree/lib/python3.9/site-packages/read2tree-0.1.2-py3.9.egg/read2tree/Aligner.py", line 286, in _align_worker
    alignment = mafft_wrapper()
  File "/netscratch/dep_mercier/grp_underwood/software2/anaconda3/envs/read2tree/lib/python3.9/site-packages/read2tree-0.1.2-py3.9.egg/read2tree/wrappers/aligners/mafft.py", line 105, in __call__
    raise WrapperError('Mafft did not compute any alignments. StdErr: {}'.format(error))
read2tree.wrappers.WrapperError: Mafft did not compute any alignments. StdErr: outputhat23=16
treein = 0
compacttree = 0
stacksize: 8192 kb
generating a scoring matrix for nucleotide (dist=200) ... done
=========================================================================
=========================================================================
===
=== Alphabet 'i' is unknown.
=== Please check site 2 in sequence 1.
===
=== To make an alignment that has unusual characters (U, @, #, etc), try
=== % mafft --anysymbol input > output
===
=========================================================================
=========================================================================
Illegal character i
"""

[nohup.txt](https://github.com/DessimozLab/read2tree/files/9357245/nohup.txt)
I have attached the nohup.txt file for the full error log.

The following command & input was used:
```
read2tree --standalone_path marker_genes/ --output_path output/ --reference  
read2tree --standalone_path marker_genes/ --output_path output/ --threads 10 --read_type long --reads specie1.fq
read2tree --standalone_path marker_genes/ --output_path output/ --threads 10 --read_type long --reads specie2.fq
read2tree --standalone_path marker_genes/ --output_path output/ --threads 10 --read_type long --reads specie3.fq
read2tree --standalone_path marker_genes/ --output_path output/ --threads 10 --read_type long --reads specie4.fq
read2tree --standalone_path marker_genes/ --output_path output/ --merge_all_mappings --tree
```
marker_genes were exported using OMAbrowser with minimum fraction 0.8 and maximum number of markers -1.

Any idea what could be causing this issue and how it could be resolved? The .fq files were previously aligned using pbmm2 and minimap2 without issues.
I am happy to provide additional information.

All the best,
Willem

**Comment by smajidian** [comment]
Dear Willem 
Thanks for using our tool and contacting us.

I think that happens when there is an unusual amino acid in the sequence file analysed by mafft.  I've just added the `--anysymbol` argument to our mafft wrapper code and make it true as default. So now I expect it to work.

Could you possibly pull the updated read2tree code and give it another try?  

Best regards,
Sina

**Comment by wrengs** [comment]
Dear Sina,

Thank you kindly for the quick reply.

Attached here is the mplog 
[mplog.log](https://github.com/DessimozLab/read2tree/files/9359443/mplog.log)

I am not sure, the first line command `read2tree --standalone_path marker_genes/ --output_path output/ --reference` seems to run normally as the `output/` folder is created containing subfolders 01_ref_ogs_aa, 01_ref_ogs_dna, 02_ref_dna etc.
From the previously attached nohup.txt file, the error starts showing up after alignment is initiated: 

Loading OGs: 100%|██████████| 14506/14506 [47:20<00:00,  5.11 OGs/s]
2022-08-16 14:19:06,830 - read2tree.OGSet - INFO - : Gathering of DNA seq for 14506 OGs took 2840.682651281357.
--- Generating reference for mapping ---

Loading records:   0%|          | 0/14506 [00:00<?, ? record/s]
Loading records:  79%|███████▉  | 11486/14506 [00:00<00:00, 114844.50 record/s]
Loading records: 100%|██████████| 14506/14506 [00:00<00:00, 116783.51 record/s]
2022-08-16 14:19:06,956 - read2tree.ReferenceSet - INFO - : Extracted 2 reference species form 14506 ogs took 0.12563514709472656
--- Alignment of 14506 OGs ---
2022-08-16 14:19:23,896 - read2tree.wrappers.aligners.mafft - WARNING - is MAFFT_BINARIES set correctly: 
multiprocessing.pool.RemoteTraceback: 

Regarding the names and first few lines of files within the `marker_genes`
Please find attached the first 10 lines per file, for the following 3 files:
OMAGroup_1000062.fa
OMAGroup_1000066.fa
OMAGroup_1000068.fa
[OMAGroup_1000066.txt](https://github.com/DessimozLab/read2tree/files/9359521/OMAGroup_1000066.txt)
[OMAGroup_1000068.txt](https://github.com/DessimozLab/read2tree/files/9359522/OMAGroup_1000068.txt)
[OMAGroup_1000062.txt](https://github.com/DessimozLab/read2tree/files/9359523/OMAGroup_1000062.txt)

All the best,
Willem

**Comment by alpae** [comment]
Hi @wrengs 
from the error it seems that one of the nucleotide in the alignment contains an unknown or at least unusual value. seems pretty strange given you could process the fastq files previously.  any chance you still have the data that is in `/scratch/tmp8z_6bupz`? I guess within that folder we could find the suspicious case. otherwise, we will need to try to identify the cause in a different way.
cheers Adrian

**Comment by wrengs** [comment]
Hi Adrian,

Yes, according to the logs the unusual value seems to be an "i", which is quite strange.
As a sanity check, I looked for any occurrences of "i" within the sequence of any of the input .fq files `seqkit grep -s -i -p i *.fq`
This resulted in no hits at all, whereas searching for any of the nucleotides did (as it should).

Unfortunately, data is not there anymore. I will set off another run using just a single input to see whether I can reproduce the error and fish out the data.

Cheers,
Willem

**Comment by alpae** [comment]
Hi Willem,

I see, I think these files might get removed directly. would it be possible to send us somehow a dataset that fails for you (maybe just a single reads file, and the marker_genes you used?) you can also send that privately by email or send us a wetransfer link or whatever is convenient for you). We'd like to try to hunt down that bug.

Have a nice weekend. Adrian

**Comment by wrengs** [comment]
Hi Adrian,

Thanks a lot for being so actively involved in trying to solve the issue!
Below are the links for the marker files and single reads file.

Markers file: 
https://wetransfer.com/downloads/ddcb21c39810c8dd2983953e174e642920220819104624/ef8ab4d18c1fefc67e785c23ea4d0d3820220819104643/8cae9c 

The reads file:
https://gigamove.rwth-aachen.de/en/download/9d9e25b8723a34325735032f93b8e7a1

Markers were unpacked using: `gunzip -c marker_genes_13212092f806f494bfb6f15f863b041f.tgz | tar xvf -`, which generated the `marker_genes/` folder
The input reads file `MB.fq` was created by subsampling https://www.ebi.ac.uk/ena/browser/view/ERX6293756 using `zcat input.fastq.gz | seqkit sample --rand-seed 11 -p 0.1 -o MB.fq.gz`

Please let me know if the download worked or if I can help providing any further information.

Thanks again and have a nice weekend!
Willem

**Comment by smajidian** [comment]
Dear Willem, thanks for sharing the files. We are working on this and we'll inform  you soon.

**Comment by alpae** [comment]
Hi @wrengs
I could reproduce your problem and implemented a fix for it. essentially, one orthologous group was very G heavy and mafft interpreted this to be a nucleic sequence. The fix now makes sure that mafft uses the amino acids mode.  Your dataset runs now smoothly for me. 

Could you please check with the latest version of read2tree from the github repository that the it works now also for you?
Cheers Adrian

**Comment by wrengs** [comment]
Dear Sina and Adrian,

Thank you both for your dedication and flexibility in solving the issue. 

I re-installed the latest version from the github repository and am currently running the dataset re-using the previous commands. So far mafft seems to be running smoothly and is now passing the step where the error previously occurred.
```
2022-08-24 12:29:03,281 - read2tree.OGSet - INFO - : Gathering of DNA seq for 14506 OGs took 3132.382365465164.
--- Generating reference for mapping ---

Loading records:   0%|          | 0/14506 [00:00<?, ? record/s]
Loading records:  78%|███████▊  | 11331/14506 [00:00<00:00, 113287.69 record/s]
Loading records: 100%|██████████| 14506/14506 [00:00<00:00, 114964.77 record/s]
2022-08-24 12:29:03,411 - read2tree.ReferenceSet - INFO - : Extracted 2 reference species form 14506 ogs took 0.12831830978393555
--- Alignment of 14506 OGs ---
2022-08-24 12:29:07,130 - read2tree.Aligner - INFO - aligning OG OG758431 with 2 proteins

```

If preferred, I am happy to update my comment once everything has finished.

All the best,
Willem
