### ISSUE TITLE
Question: What is the question mark in the amoni acid sequence?

### ISSUE THREAD

**Issue by YuWang07** [DessimozLab/read2tree#63]
Dear author,

I notice there are multi-sites containing question marks. Does that mean the missing information? How to deal with these uncertain sites in the phylogenetic tree?

Any help will be appreciated. 

Best Regards,
Yu

**Comment by alpae** [comment]
Hi @YuWang07 

yes, the ? symbol is used to indicate that for this locus of the given species, no reads were mapped. Tree building methods usually handle them out of the box in the same way as gaps. 

Cheers Adrian
