### ISSUE TITLE
OMA not generating the marker genes

### ISSUE THREAD

**Issue by evo-eco-gen** [DessimozLab/read2tree#64]
Hello,

I have not been  able to produce a set of marker genes with OMA since about the end of June. It just gets stuck on a job: this is surprising, I only ask for a set of 5 rodent species. I am rather in need of a small marker set, with the mammalia markers you provided my job would take 10 CPU-months.
1. Is OMA OK? Example failing jobs: https://omabrowser.org/oma/markers/a1c5517d1f98b966010291688f9ed597/?
https://omabrowser.org/oma/markers/2cba11139be9c3e79fe38fce1642b7b3/?

2. Is there a way to choose reference species when running read2tree?
Thanks, KK

**Comment by alpae** [comment]
Dear @evo-eco-gen 

thanks for reaching out. indeed, the maker export functionality somehow got stuck. I've reactivated the workers now and your dataset is now already ready. exporting markers should be normally really quick - it shouldn't take more than a few minutes even for relatively big datasets.

Your second question I don't really understand. 

Best Adrian

**Comment by evo-eco-gen** [comment]
Thank you Adrian!
As for my 2nd question: read2tree has a few options like "--ignore_species", I was wondering if that's a way to control which reference species are included in the analysis.

**Comment by alpae** [comment]
ok, I see. those options were mostly implemented during the development phase. The `--ignore_species` option for example was used to use a subset of the markers from an OMA standalone run. We rather recommend to build a tailored set of reference groups - that's also why we implemented a direct export from the OMA Browser website. 

I hope this answers your question. Cheers Adrian

**Comment by evo-eco-gen** [comment]
Thank you, you did answer all my questions!
