### ISSUE TITLE
--standalone_path error when using docker

### ISSUE THREAD

**Issue by ailtonpcf** [DessimozLab/read2tree#9]
I was having the following error:

`usage: read2tree [-h] [--version] [--output_path OUTPUT_PATH]
                 --standalone_path STANDALONE_PATH [--reads READS [READS ...]]
                 [--read_type READ_TYPE] [--threads THREADS] [--split_reads]
                 [--split_len SPLIT_LEN] [--split_overlap SPLIT_OVERLAP]
                 [--split_min_read_len SPLIT_MIN_READ_LEN] [--sample_reads]
                 [--genome_len GENOME_LEN] [--coverage COVERAGE]
                 [--min_cons_coverage MIN_CONS_COVERAGE]
                 [--dna_reference DNA_REFERENCE] [--sc_threshold SC_THRESHOLD]
                 [--ngmlr_parameters NGMLR_PARAMETERS] [--check_mate_pairing]
                 [--debug] [--sequence_selection_mode SEQUENCE_SELECTION_MODE]
                 [-s SPECIES_NAME] [--tree] [--merge_all_mappings] [-r]
                 [--min_species MIN_SPECIES] [--single_mapping SINGLE_MAPPING]
                 [--ref_folder REF_FOLDER]
                 [--remove_species_mapping REMOVE_SPECIES_MAPPING]
                 [--remove_species_ogs REMOVE_SPECIES_OGS] [--keep_all_ogs]
                 [--ignore_species IGNORE_SPECIES]
read2tree: error: the following arguments are required: --standalone_path`

Commenting the last two lines of the dockerfile and building the image again solved my problem:

`ENTRYPOINT ["read2tree"]

CMD ["-h"] `

**Comment by alpae** [comment]
Hi @ailtonpcf 

I guess you tried to run the docker including the read2tree command, which is not necessary. you should simply call it with the command line arguments after the image name, see https://github.com/DessimozLab/read2tree#run-test-example-using-docker
